### ISSUE TITLE
file ending doesn't change in moodle text field

### ISSUE THREAD

**Issue by lars-wars** [ndunand/moodle-filter_html5avtomp4#9]
Hello there, 
at first I want to say this is a great plugin, thank you. 

We found just one issue and perhaps you have a solution for it: 
When we record an audio file in a text field the conversion through the plugin hmtl5avmp4 and ffmpeg takes place (because when you change the file ending from filename.ogg to filename.m4a, the .m4a file can be playedm also the files are available in the files folder), but in the text field in moodle the link still ends in .ogg instead of .m4a. 

Is there any way that the filename will be saved in the text field with the correct file ending like filename.m4a? 

Thanks in advance.

**Comment by ndunand** [comment]
Hello @lars-wars ,

Thanks for your feedback. Indeed this is how the plugin works, by design. Moodle filters actually do not change text content, but rather "filter" it, i.e. output some modification based on the original text.

In the case of this plugin, the filter does several things :
 - convert the file to M4A (for audio) or MP4 (for video) : this occurs only once ; the file is then placed "next to" the original non-mp4 file ;
 - change the source file extension (on-the-fly at display time) : this occurs on each page display, and as the mp4 file exists the effect of this is to use the mp4 file for playback (audio or video)

What this filter does not do is alter the original text, so if you visit the text editor again, you will see:
 - the text still links to the original ogg file
 - the original OGG (or WEBM) file is still present
 - the MP4 (or M4A) file has been added to the editor files.

The consequence of this is that if you were to deactivate the filter afterwards, the MP4 file would still be present, but the browser would not try to read it (because the OGG file is still referenced in the text).

This is indeed a shortcoming of this method, but it's the one I could come up with that works pretty much anywhere.

The advantage of this is that if you visit the page with a browser (say Chrome) which "prefers" OGG, it still has the option to do so. And when you visit with Safari (for instance), it finds the MP4 file. So yes, we have two files instead of one, but all browsers (and users) are happy.

Cheers,

**Comment by lars-wars** [comment]
Hello Nicolas,

thank you for the comprehensive answer, this helps a lot in understanding the connection between moodle, the filter and the converter! Then we will continue like this as the filter works just fine as it is.

Perhaps we will give a hint to the user, so they could amend the file ending (if needed).

Again, thanks a lot for your great work.
